### ISSUE TITLE
Table aggregation: Token expires while running long aggregations

### ISSUE THREAD

**Issue by AishaAiak** [equinor/sumo-tableaggregator#11]
**Repro Steps**
![image](https://github.com/equinor/sumo-tableaggregator/assets/54443750/9b43886d-8f51-48f5-ae61-cf9a5cafc574)

**Comment from Ove on devops US**
Seems to happen at exactly 12 hours which I assume is the token duration. Need to either split into more jobs or refresh the token somehow

**Comment by equinor-ruaj** [comment]
https://github.com/equinor/sumo-fmu-aggregation-service/pull/136 closes
