### ISSUE TITLE
Table aggregation - get Snorre tables to work

### ISSUE THREAD

**Issue by AishaAiak** [equinor/sumo-tableaggregator#12]
- [x] Fix expiration of token when running in radix
- [x] Rewrite to limit time usage on huge tables
- [x] Have a look at the faults, seems wrong
- [x] Include Parameters.txt results
- [x] integration  test for table aggregation code
- [x] Merge latest changes from add_psutil
- [ ] Merge service and aggregation repos

**Comment by equinor-ruaj** [comment]
`sumo-tableaggregator` will be merged into the aggregation service in a separate issue
