### ISSUE TITLE
Integrate code with fmu-dataio and fmu-sumo.uploader and thereby improve metadata

### ISSUE THREAD

**Issue by daniel-sol** [equinor/sumo-tableaggregator#50]
So far all metadata are generated by this code, and bypass fmu-dataio completely.
This should be changed, 
Whether this should be done prior to integration with aggregation code is a point of discussion
Integration with fmu-dataio would simplify code, and iron out some bugs

* Class Meta something could be removed, only needed because something needs to take care of what AggregatedData does for fmu-dataio
* There are sections in source._sumo that are not being populated, this is done either by fmu-dataio or by the uploader.

**Comment by equinor-ruaj** [comment]
Code moved to https://github.com/equinor/sumo-fmu-aggregation-service
Issue re-created there: https://github.com/equinor/sumo-fmu-aggregation-service/issues/246
